name: Custom Workflow

on:
  push:
    branches: [develop]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
      - name: Install and Test
        run: |
          npm install
          npm test
        working-directory: ./sample-app